---
version: '3'
services:
  registry-mirror:
    image: registry-mirror:latest
    container_name: registry-mirror
    volumes:
      - /var/registry-mirror/config.yml:/config.yml
      - /var/certs:/certs:ro
    environment:
      - CONFIG=/config.yml
      - INTERVAL=600
    restart: always
    logging: &logging
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "4"

  registry:
    container_name: registry
    restart: always
    image: registry:2.7.1
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:445
    ports:
      - '445:445'
    volumes:
      - /var/registry/registry:/var/lib/registry
      - /var/certs:/certs:ro
    logging:
      <<: *logging
